system:
  gpu-id: 0
  traces: ../data
  processed: processed
  model: model

teacher:
  number: 1
  model: d

student:
  model: d

train:
  epochs: 50
  lr: 0.0002
  gamma: 0.1
  step-size: 20
  early-stop: 10
  alpha: 0.5
  temperature: 5

model:
  tch_d:
    channels: 1
  tch_r:
    dim: 64
    channels: 1
  tch_v:
    dim: 256
    depth: 8
    heads: 10
    mlp-dim: 256
    channels: 1
  stu_d:
    channels: 1
  stu_r:
    dim: 4
    channels: 1
  stu_v:
    dim: 16
    depth: 2
    heads: 2
    mlp-dim: 16
    channels: 1

apps:
  app: 473.astar-s1.txt.xz

trace-data:
  train: 20
  total: 30
  skip: 0
  batch-size: 256

hardware:
  block-bits: 6
  total-bits: 64
  look-back: 9
  pred-forward: 128
  page-bits: 12
  delta-bound: 128
  split-bits: 6
  filter-size: 16
  bitmap-size: 256 # 2 * delta-bound
  block-num-bits: 58 # total-bits - block-bits
