stages:
  preprocess:
    cmd: python src/preprocess.py
    vars:
      - g.yaml
    deps:
      - ${system.traces}/${apps.app}
      - src/preprocess.py
      - src/data_loader.py
    params:
      - g.yaml:
        - system
        - apps.app
        - teacher.number
        - trace-data
        - hardware
    outs:
      - processed/train_loader_1
      - processed/test_loader_1
      - processed/test_df_1  
      - processed/train_loader_2
      - processed/test_loader_2
      - processed/test_df_2
      - processed/train_loader_3
      - processed/test_loader_3
      - processed/test_df_3
      - processed/train_loader_4
      - processed/test_loader_4
      - processed/test_df_4
      - processed/train_loader_5
      - processed/test_loader_5
      - processed/test_df_5
      - processed/train_loader_stu
      - processed/test_loader_stu
      - processed/test_df_stu

  train-tch-1:
    cmd: python src/train_tch.py 1
    vars:
      - g.yaml    
    deps:
      - processed/train_loader_1
      - processed/test_loader_1
      - src/train_tch.py
    params:
      - g.yaml:  
        - teacher.model_1
        - model.tch_${teacher.model_1}
        - system
        - hardware
        - train
    metrics:
      - res/plots/metrics/train_tch_1/test_loss.tsv:
          cache: false
      - res/plots/metrics/train_tch_1/train_loss.tsv:
          cache: false
    outs:
      - model/teacher_1.pth

  train-tch-2:
    cmd: python src/train_tch.py 2
    vars:
      - g.yaml
    deps:
      - processed/train_loader_2
      - processed/test_loader_2
      - src/train_tch.py
    params:
      - g.yaml:  
        - teacher.model_2
        - model.tch_${teacher.model_2}
        - system
        - hardware
        - train
    metrics:
      - res/plots/metrics/train_tch_2/test_loss.tsv:
          cache: false
      - res/plots/metrics/train_tch_2/train_loss.tsv:
          cache: false
    outs:
      - model/teacher_2.pth

  train-tch-3:
    cmd: python src/train_tch.py 3
    vars:
      - g.yaml
    deps:
      - processed/train_loader_3
      - processed/test_loader_3
      - src/train_tch.py
    params:
      - g.yaml:  
        - teacher.model_3
        - model.tch_${teacher.model_3}
        - system
        - hardware
        - train
    metrics:
      - res/plots/metrics/train_tch_3/test_loss.tsv:
          cache: false
      - res/plots/metrics/train_tch_3/train_loss.tsv:
          cache: false
    outs:
      - model/teacher_3.pth
  
  train-tch-4:
    cmd: python src/train_tch.py 4
    vars:
      - g.yaml
    deps:
      - processed/train_loader_4
      - processed/test_loader_4
      - src/train_tch.py
    params:
      - g.yaml:  
        - teacher.model_4
        - model.tch_${teacher.model_4}
        - system
        - hardware
        - train
    metrics:
      - res/plots/metrics/train_tch_4/test_loss.tsv:
          cache: false
      - res/plots/metrics/train_tch_4/train_loss.tsv:
          cache: false
    outs:
      - model/teacher_4.pth

  train-tch-5:
    cmd: python src/train_tch.py 5
    vars:
      - g.yaml
    deps:
      - processed/train_loader_5
      - processed/test_loader_5
      - src/train_tch.py
    params:
      - g.yaml:  
        - teacher.model_5
        - model.tch_${teacher.model_5}
        - system
        - hardware
        - train
    metrics:
      - res/plots/metrics/train_tch_5/test_loss.tsv:
          cache: false
      - res/plots/metrics/train_tch_5/train_loss.tsv:
          cache: false
    outs:
      - model/teacher_5.pth
      
  validate-tch-1:
    cmd: python src/validate_tch.py 1
    vars:
      - g.yaml
    deps:
      - processed/test_loader_1
      - processed/test_df_1
      - model/teacher_1.pth
      - src/validate_tch.py
    params:
      - g.yaml:
        - teacher.model_1
        - model.tch_${teacher.model_1}
        - apps.app
        - system
        - hardware
    metrics:
      - res/teacher_1.json:
          cache: false

  validate-tch-2:
    cmd: python src/validate_tch.py 2
    vars:
      - g.yaml
    deps:
      - processed/test_loader_2
      - processed/test_df_2
      - model/teacher_2.pth
      - src/validate_tch.py
    params:
      - g.yaml:
        - teacher.model_2
        - model.tch_${teacher.model_2}
        - apps.app
        - system
        - hardware
    metrics:
      - res/teacher_2.json:
          cache: false

  validate-tch-3:
    cmd: python src/validate_tch.py 3
    vars:
      - g.yaml
    deps:
      - processed/test_loader_3
      - processed/test_df_3
      - model/teacher_3.pth
      - src/validate_tch.py
    params:
      - g.yaml:
        - teacher.model_3
        - model.tch_${teacher.model_3}
        - apps.app
        - system
        - hardware
    metrics:
      - res/teacher_3.json:
          cache: false

  validate-tch-4:
    cmd: python src/validate_tch.py 4
    vars:
      - g.yaml
    deps:
      - processed/test_loader_4
      - processed/test_df_4
      - model/teacher_4.pth
      - src/validate_tch.py
    params:
      - g.yaml:
        - teacher.model_4
        - model.tch_${teacher.model_4}
        - apps.app
        - system
        - hardware
    metrics:
      - res/teacher_4.json:
          cache: false

  validate-tch-5:
    cmd: python src/validate_tch.py 5
    vars:
      - g.yaml
    deps:
      - processed/test_loader_5
      - processed/test_df_5
      - model/teacher_5.pth
      - src/validate_tch.py
    params:
      - g.yaml:
        - teacher.model_5
        - model.tch_${teacher.model_5}
        - apps.app
        - system
        - hardware
    metrics:
      - res/teacher_5.json:
          cache: false

  train-stu:
    cmd: python src/train_stu.py
    vars:
      - g.yaml
    deps:
      - model/teacher_1.pth
      - model/teacher_2.pth
      - model/teacher_3.pth
      - model/teacher_4.pth
      - model/teacher_5.pth
      - processed/train_loader_stu
      - processed/test_loader_stu
      - src/train_stu.py
    params:
      - g.yaml:
        - student.model
        - model.stu_${student.model}
        - teacher.model_1
        - model.tch_${teacher.model_1}
        - teacher.model_2
        - model.tch_${teacher.model_2}
        - teacher.model_3
        - model.tch_${teacher.model_3}
        - teacher.model_4
        - model.tch_${teacher.model_4}
        - teacher.model_5
        - model.tch_${teacher.model_5}
        - system
        - hardware
        - train
    metrics:
      - res/plots/metrics/train_stu/test_loss.tsv:
          cache: false
      - res/plots/metrics/train_stu/train_loss.tsv:
          cache: false
    outs:
      - model/student.pth

  validate-stu:
    cmd: python src/validate_stu.py
    vars:
      - g.yaml
    deps:
      - processed/test_loader_stu
      - processed/test_df_stu
      - model/student.pth
      - src/validate_stu.py
    params:
      - g.yaml:    
        - student.model
        - model.stu_${student.model}
        - apps.app
        - system
        - hardware
    metrics:
      - res/student.json:
          cache: false

plots:
  - train-tch-1:
      y:
        res/plots/metrics/train_tch_1/train_loss.tsv: train_tch_1/train_loss
        res/plots/metrics/train_tch_1/test_loss.tsv: train_tch_1/test_loss
      y_label: loss
  - train-tch-2:
      y:
        res/plots/metrics/train_tch_2/train_loss.tsv: train_tch_2/train_loss
        res/plots/metrics/train_tch_2/test_loss.tsv: train_tch_2/test_loss
      y_label: loss
  - train-tch-3:
      y:
        res/plots/metrics/train_tch_3/train_loss.tsv: train_tch_3/train_loss
        res/plots/metrics/train_tch_3/test_loss.tsv: train_tch_3/test_loss
      y_label: loss
  - train-tch-4:
      y:
        res/plots/metrics/train_tch_4/train_loss.tsv: train_tch_4/train_loss
        res/plots/metrics/train_tch_4/test_loss.tsv: train_tch_4/test_loss
      y_label: loss
  - train-tch-5:
      y:
        res/plots/metrics/train_tch_5/train_loss.tsv: train_tch_5/train_loss
        res/plots/metrics/train_tch_5/test_loss.tsv: train_tch_5/test_loss
      y_label: loss
  - train-stu:
      y:
        res/plots/metrics/train_stu/train_loss.tsv: train_stu/train_loss
        res/plots/metrics/train_stu/test_loss.tsv: train_stu/test_loss
      y_label: loss

    


